from elasticsearch import Elasticsearch

# Password for the 'elastic' user generated by Elasticsearch
ELASTIC_PASSWORD = "6nV9Iaz6k97tZt2Ftd4J"
INDEX = "case-data"

# Create the client instance
es = Elasticsearch(
    "https://localhost:9200",
    ca_certs="./http_ca.crt",
    basic_auth=("elastic", ELASTIC_PASSWORD),
)

# Successful response!
print(es.info())
